name: Deploy to GitHub Pages

on:
  schedule:
    - cron: "0 */4 * * *" # Every 4 hours
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: yezz123/setup-uv@v4

      - name: Install Dependencies
        run: |
          uv sync --locked --extra dev

      - name: Set up env
        run: |
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run feed.py
        run: |
          uv run src/feed/feed.py

      - name: Check for changes and push if needed
        run: |
          git config --global user.name 'JacobCoffee'
          git config --global user.email 'jacob@z7x.org'
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Update static files"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/feed/output
          publish_branch: gh-pages
