name: Deploy to GitHub Pages

on:
  schedule:
    - cron: "0 */4 * * *" # Every 4 hours
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: yezz123/setup-uv@v4

      - name: Install Dependencies
        run: |
          uv sync --locked --extra dev

      - name: Set up env
        run: |
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      - name: Build Tailwind CSS
        run: |
          echo "Building Tailwind CSS..."
          NODE_ENV=.nodeenv
          NODE_ENV_BIN=$NODE_ENV/bin

          if [ ! -d "$NODE_ENV" ]; then
            uv run nodeenv --node=22.6.0 $NODE_ENV
          fi

          . $NODE_ENV_BIN/activate

          if [ ! -d "node_modules" ]; then
            npm install
          fi

          npx tailwindcss -i ./src/styles/tailwind.css -o ./src/feed/output/styles.css --minify
          echo "Done"

      - name: Run feed.py
        run: |
          uv run src/feed/feed.py

      - name: Check for changes and push if needed
        run: |
          git config --global user.name 'JacobCoffee'
          git config --global user.email 'jacob@z7x.org'
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Update static files"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/feed/output
          publish_branch: gh-pages
